# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:45
from __future__ import unicode_literals

import bid_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(default=bid_api.models.create_random_secret, max_length=64),
        ),
    ]
