# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_api', '0002_webhook_secret_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='timeout',
            field=models.IntegerField(default=3, help_text='Timeout for HTTP calls to this webhook, in seconds.'),
        ),
    ]
