# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid_api', '0003_webhook_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookQueuedCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(help_text='The payload to POST to the webhook')),
                ('error_code', models.IntegerField(blank=True, help_text='The HTTP status code received when POSTing')),
                ('error_msg', models.TextField(blank=True, help_text='The HTTP response received when POSTing')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='bid_api.Webhook')),
            ],
            options={
                'verbose_name': 'Webhook Queued Call',
                'verbose_name_plural': 'Webhook queue',
            },
        ),
    ]
