# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_api', '0004_webhookqueuedcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='last_flush_attempt',
            field=models.DateTimeField(help_text='Records when we last tried to flush this queue', null=True),
        ),
    ]
