version:            '3.4'
services:
    blender-id:
        image:          blenderinstitute/blender-id:latest
        container_name: blender-id
        restart:        always
        environment:
            # Use stunnel to provide a TLS tunnel. See
            # https://gitlab.com/blender-institute/workstation-setup-webdev/tree/master/https
            # for more info.
            HTTPS: 1
        depends_on:
            - mysql
        volumes:
            # format:     HOST:CONTAINER
            - /var/www/blender-id/settings:/var/www/settings:ro
            - /var/www/blender-id/log:/var/log
            - /var/www/blender-id/postfix:/var/spool/postfix
            - /var/www/blender-id/media:/var/www/blender-id/media
        ports:
            - "80:80"
        extra_hosts:
            - "id.blender.org:127.0.0.1"
            - "id.local:127.0.0.1"
        logging:
            driver:                "json-file"
            options:
                max-size:            "200k"
                max-file:            "20"

    mysql:
        image: mysql:5.7
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - /var/www/mysql:/var/lib/mysql
        restart: "always"
        labels:
            traefik.enable: "false"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        logging:
            driver:                "json-file"
            options:
                max-size:            "200k"
                max-file:            "20"
