# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0010_oauth2_model_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2application',
            name='notes',
            field=models.TextField(blank=True, help_text='Information about this application, for staff only, not to present on frontend.'),
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='url',
            field=models.URLField(blank=True, help_text="URL to display on 'access' page for users."),
        ),
    ]
