# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0012_user_public_roles_as_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_roles_as_string',
            field=models.CharField(blank=True, default='', help_text='String representation of public roles, for comparison in webhooks', max_length=255, verbose_name='Public roles as string'),
        ),
    ]
