# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 09:36
from __future__ import unicode_literals

import bid_main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bid_main', '0017_user_nickname_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(
                error_messages={'unique': 'That nickname is already used by someone else.'},
                help_text='A short (one-word) name that can be used to address you. '
                          '80 characters or fewer. Letters, digits, and ./+/-/_ only.',
                max_length=80,
                unique=True,
                validators=[bid_main.models.UnicodeNicknameValidator()],
                verbose_name='nickname'),
        ),
    ]
