# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0018_user_nickname_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_policy_agreed',
            field=models.DateTimeField(help_text='Date when this user agreed to our privacy policy.', null=True, verbose_name='privacy policy agreed'),
        ),
    ]
