# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 08:23
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0021_django_oauth_toolkit_110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='badge_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, height_field='badge_img_height', help_text='Visual representation of a badge.', null=True, upload_to='badges', width_field='badge_img_width'),
        ),
    ]
