# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0022_badges_sorl_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='badge_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, height_field='badge_img_height', help_text='Visual representation of a badge.', null=True, upload_to='badges', verbose_name='Badge image', width_field='badge_img_width'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_badge',
            field=models.BooleanField(default=False, help_text='Note that a roles is only actually used as a badge when this checkbox is enabled <strong>and</strong> it has a badge image.'),
        ),
    ]
