# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0023_roles_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_badges',
            field=models.ManyToManyField(blank=True, to='bid_main.Role'),
        ),
    ]
