# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0024_user_private_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_badges',
            field=models.ManyToManyField(blank=True, help_text='Badges marked as "private" by the user. Can contain badges they do not have at the moment; this is fine.', to='bid_main.Role'),
        ),
    ]
