# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0025_user_private_badges_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privacy_policy_agreed',
            field=models.DateTimeField(blank=True, help_text='Date when this user agreed to our privacy policy.', null=True, verbose_name='privacy policy agreed'),
        ),
    ]
