# Generated by Django 2.0.13 on 2019-05-07 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0026_user_pp_agreed_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_badges',
            field=models.ManyToManyField(blank=True, help_text='Badges marked as "private" by the user. Can contain badges they do not have at the moment; this is fine.', limit_choices_to={'is_badge': True}, to='bid_main.Role'),
        ),
        migrations.AlterField(
            model_name='usernote',
            name='creator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
