# Generated by Django 2.2.7 on 2019-11-05 10:32

import bid_main.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_main', '0028_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=bid_main.fields.AvatarField(blank=True, null=True, upload_to='user-avatars'),
        ),
    ]
